@echo off
@echo This cmd file creates a Data API Builder configuration based on the chosen database objects.
@echo To run the cmd, create an .env file with the following contents:
@echo dab-connection-string=your connection string
@echo ** Make sure to exclude the .env file from source control **
@echo **
dotnet tool install -g Microsoft.DataApiBuilder
dab init -c dab-config.json --database-type mssql --connection-string "@env('dab-connection-string')" --host-mode Development
@echo Adding tables
dab add "Role" --source "[Authorization].[Role]" --fields.include "RoleId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "User" --source "[Authorization].[User]" --fields.include "UserId,LoginName,FirstName,LastName,EmailAddress,JobTitle,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "UserAttribute" --source "[Authorization].[UserAttribute]" --fields.include "UserAttributeId,UserId,UserAttributeTypeId,UserAttributeValue,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "UserAttributeType" --source "[Authorization].[UserAttributeType]" --fields.include "UserAttributeTypeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "UserRole" --source "[Authorization].[UserRole]" --fields.include "UserRoleId,UserId,RoleId,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "BillOfMaterial" --source "[dbo].[BillOfMaterial]" --fields.include "BillOfMaterialId,Name,Description,PartId,EffectiveStartDate,EffectiveStartDateUtc,EffectiveEndDate,EffectiveEndDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "BillOfMaterialPart" --source "[dbo].[BillOfMaterialPart]" --fields.include "BillOfMaterialPartId,BillOfMaterialId,PartId,Quantity,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "BillOfProcess" --source "[dbo].[BillOfProcess]" --fields.include "BillOfProcessId,Name,Description,PartId,EffectiveStartDate,EffectiveStartDateUtc,EffectiveEndDate,EffectiveEndDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "BillOfProcessProcess" --source "[dbo].[BillOfProcessProcess]" --fields.include "BillOfProcessProcessId,BillOfProcessId,ProcessId,Sequence,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "BillOfProcessProcessWorkElement" --source "[dbo].[BillOfProcessProcessWorkElement]" --fields.include "BillOfProcessProcessWorkElementId,BillOfProcessProcessId,WorkElementTypeId,Name,Sequence,IsRequired,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "BillOfProcessProcessWorkElementAttribute" --source "[dbo].[BillOfProcessProcessWorkElementAttribute]" --fields.include "BillOfProcessProcessWorkElementAttributeId,BillOfProcessProcessWorkElementId,WorkElementTypeAttributeId,AttributeValue,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Container" --source "[dbo].[Container]" --fields.include "ContainerId,ContainerTypeId,InventoryLocationId,SerialNumber,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "ContainerOrderItemUnit" --source "[dbo].[ContainerOrderItemUnit]" --fields.include "ContainerOrderItemUnitId,ContainerId,OrderItemUnitId,PositionOnContainer,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "ContainerType" --source "[dbo].[ContainerType]" --fields.include "ContainerTypeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Customer" --source "[dbo].[Customer]" --fields.include "CustomerId,Name,Address,PostalCode,City,StateOrProvince,Country,PhoneNumber,EmailAddress,ContactName,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Defect" --source "[dbo].[Defect]" --fields.include "DefectId,DefectCategoryId,Name,Description,IsActive,IsReworkable,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "DefectCategory" --source "[dbo].[DefectCategory]" --fields.include "DefectCategoryId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "DefectProcess" --source "[dbo].[DefectProcess]" --fields.include "DefectProcessId,DefectId,ProcessId,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "FinishedGood" --source "[dbo].[FinishedGoods]" --fields.include "FinishedGoodsId,ContainerId,ContainerQuantityAtTransactionDate,IsReturnedToProduction,TransactionDate,TransactionDateUtc,ReturnToProductionDate,ReturnToProductionDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "InventoryItem" --source "[dbo].[InventoryItem]" --fields.include "InventoryItemId,InventoryItemTypeId,InventoryLocationId,PartId,SupplierId,SerialNumber,Quantity,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "InventoryItemAttribute" --source "[dbo].[InventoryItemAttribute]" --fields.include "InventoryItemAttributeId,InventoryItemId,ItemAttributeTypeId,AttributeValue,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "InventoryItemScrap" --source "[dbo].[InventoryItemScrap]" --fields.include "InventoryItemScrapId,InventoryItemId,DefectId,UserId,Quantity,Comment,ScrapDate,ScrapDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "InventoryItemType" --source "[dbo].[InventoryItemType]" --fields.include "InventoryItemTypeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "InventoryLocation" --source "[dbo].[InventoryLocation]" --fields.include "InventoryLocationId,InventoryLocationTypeId,Name,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "InventoryLocationType" --source "[dbo].[InventoryLocationType]" --fields.include "InventoryLocationTypeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "ItemAttributeType" --source "[dbo].[ItemAttributeType]" --fields.include "ItemAttributeTypeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Order" --source "[dbo].[Order]" --fields.include "OrderId,Number,OrderStateId,CustomerId,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "OrderItem" --source "[dbo].[OrderItem]" --fields.include "OrderItemId,OrderId,FinishedPartId,Quantity,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "OrderItemAttribute" --source "[dbo].[OrderItemAttribute]" --fields.include "OrderItemAttributeId,OrderItemId,ItemAttributeTypeId,AttributeValue,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "OrderItemUnit" --source "[dbo].[OrderItemUnit]" --fields.include "OrderItemUnitId,OrderItemId,PartId,SerialNumber,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "OrderItemUnitConsumption" --source "[dbo].[OrderItemUnitConsumption]" --fields.include "OrderItemUnitConsumptionId,OrderItemUnitId,EquipmentId,UserId,BillOfProcessProcessWorkElementAttributeId,ConsumedSerialNumber,IsConsumed,ConsumedDate,ConsumedDateUtc,RemovedDate,RemovedDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "OrderItemUnitDataCollection" --source "[dbo].[OrderItemUnitDataCollection]" --fields.include "OrderItemUnitDataCollectionId,OrderItemUnitId,EquipmentId,UserId,BillOfProcessProcessWorkElementAttributeId,CollectedValue,CollectedDate,CollectedDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "OrderItemUnitScrap" --source "[dbo].[OrderItemUnitScrap]" --fields.include "OrderItemUnitScrapId,OrderItemUnitId,EquipmentId,DefectId,UserId,Comment,ScrapDate,ScrapDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "OrderItemUnitWorkElementHistory" --source "[dbo].[OrderItemUnitWorkElementHistory]" --fields.include "OrderItemUnitWorkElementHistoryId,OrderItemUnitId,BillOfProcessProcessWorkElementId,EquipmentId,WorkElementStatusId,UserId,StartDate,StartDateUtc,EndDate,EndDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "OrderState" --source "[dbo].[OrderState]" --fields.include "OrderStateId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Part" --source "[dbo].[Part]" --fields.include "PartId,PartTypeId,PartNumber,PartRevision,Description,UnitOfMeasureId,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "PartItemAttributeType" --source "[dbo].[PartItemAttributeType]" --fields.include "PartItemAttributeTypeId,PartId,ItemAttributeTypeId,IsRequired,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "PartType" --source "[dbo].[PartType]" --fields.include "PartTypeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Supplier" --source "[dbo].[Supplier]" --fields.include "SupplierId,Name,Address,PostalCode,City,StateOrProvince,Country,PhoneNumber,EmailAddress,ContactName,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "UnitOfMeasure" --source "[dbo].[UnitOfMeasure]" --fields.include "UnitOfMeasureId,Name,ShortName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "WorkElementStatus" --source "[dbo].[WorkElementStatus]" --fields.include "WorkElementStatusId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "WorkElementType" --source "[dbo].[WorkElementType]" --fields.include "WorkElementTypeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "WorkElementTypeAttribute" --source "[dbo].[WorkElementTypeAttribute]" --fields.include "WorkElementTypeAttributeId,WorkElementTypeId,Name,IsRequiredAtSetup,IsRequiredAtRun,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "WorkElementTypeAttributeListItem" --source "[dbo].[WorkElementTypeAttributeListItem]" --fields.include "WorkElementTypeAttributeListItemId,WorkElementTypeAttributeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "State" --source "[Equipment].[State]" --fields.include "StateId,Name,ShortName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "StateChange" --source "[Equipment].[StateChange]" --fields.include "StateChangeId,EquipmentId,EquipmentName,StateChangeTime,StateChangeTimeUTC,CurrentStateId,PreviousStateId,PreviousStateTimeInSeconds,LastModifiedBy,LastModifiedTime,LastModifiedTimeUTC" --permissions "anonymous:*" 
dab add "Coater" --source "[Global].[Coater]" --fields.include "CoaterId,EquipmentId,Number,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Equipment" --source "[Global].[Equipment]" --fields.include "EquipmentId,LineId,ProcessId,Name,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Line" --source "[Global].[Line]" --fields.include "LineId,UnitId,Name,DisplayName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Plant" --source "[Global].[Plant]" --fields.include "PlantId,SiteId,Name,DisplayName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Process" --source "[Global].[Process]" --fields.include "ProcessId,Number,Name,LoopNumber,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Site" --source "[Global].[Site]" --fields.include "SiteId,Name,DisplayName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "Unit" --source "[Global].[Unit]" --fields.include "UnitId,PlantId,Name,DisplayName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc" --permissions "anonymous:*" 
dab add "AuthorizationUser" --source "[History].[Authorization_User]" --fields.include "HistoryUserId,UserId,LoginName,FirstName,LastName,EmailAddress,JobTitle,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "AuthorizationUserRole" --source "[History].[Authorization_UserRole]" --fields.include "HistoryUserRoleId,UserRoleId,UserId,RoleId,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboBillOfMaterial" --source "[History].[dbo_BillOfMaterial]" --fields.include "HistoryBillOfMaterialId,BillOfMaterialId,Name,Description,PartId,EffectiveStartDate,EffectiveStartDateUtc,EffectiveEndDate,EffectiveEndDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboBillOfMaterialPart" --source "[History].[dbo_BillOfMaterialPart]" --fields.include "HistoryBillOfMaterialPartId,BillOfMaterialPartId,BillOfMaterialId,PartId,Quantity,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboBillOfProcess" --source "[History].[dbo_BillOfProcess]" --fields.include "HistoryBillOfProcessId,BillOfProcessId,Name,Description,PartId,EffectiveStartDate,EffectiveStartDateUtc,EffectiveEndDate,EffectiveEndDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboBillOfProcessProcess" --source "[History].[dbo_BillOfProcessProcess]" --fields.include "HistoryBillOfProcessProcessId,BillOfProcessProcessId,BillOfProcessId,ProcessId,Sequence,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboBillOfProcessProcessWorkElement" --source "[History].[dbo_BillOfProcessProcessWorkElement]" --fields.include "HistoryBillOfProcessProcessWorkElementId,BillOfProcessProcessWorkElementId,BillOfProcessProcessId,WorkElementTypeId,Name,Sequence,IsRequired,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboBillOfProcessProcessWorkElementAttribute" --source "[History].[dbo_BillOfProcessProcessWorkElementAttribute]" --fields.include "HistoryBillOfProcessProcessWorkElementAttributeId,BillOfProcessProcessWorkElementAttributeId,BillOfProcessProcessWorkElementId,WorkElementTypeAttributeId,AttributeValue,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboContainer" --source "[History].[dbo_Container]" --fields.include "HistoryContainerId,ContainerId,ContainerTypeId,InventoryLocationId,SerialNumber,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboContainerOrderItemUnit" --source "[History].[dbo_ContainerOrderItemUnit]" --fields.include "HistoryContainerOrderItemUnitId,ContainerOrderItemUnitId,ContainerId,OrderItemUnitId,PositionOnContainer,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboCustomer" --source "[History].[dbo_Customer]" --fields.include "HistoryCustomerId,CustomerId,Name,Address,PostalCode,City,StateOrProvince,Country,PhoneNumber,EmailAddress,ContactName,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboDefect" --source "[History].[dbo_Defect]" --fields.include "HistoryDefectId,DefectId,DefectCategoryId,Name,Description,IsActive,IsReworkable,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboDefectCategory" --source "[History].[dbo_DefectCategory]" --fields.include "HistoryDefectCategoryId,DefectCategoryId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboDefectProcess" --source "[History].[dbo_DefectProcess]" --fields.include "HistoryDefectProcessId,DefectProcessId,DefectId,ProcessId,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboFinishedGood" --source "[History].[dbo_FinishedGoods]" --fields.include "HistoryFinishedGoodsId,FinishedGoodsId,ContainerId,ContainerQuantityAtTransactionDate,IsReturnedToProduction,TransactionDate,TransactionDateUtc,ReturnToProductionDate,ReturnToProductionDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboInventoryItem" --source "[History].[dbo_InventoryItem]" --fields.include "HistoryInventoryItemId,InventoryItemId,InventoryItemTypeId,InventoryLocationId,PartId,SupplierId,SerialNumber,Quantity,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboInventoryItemAttribute" --source "[History].[dbo_InventoryItemAttribute]" --fields.include "HistoryInventoryItemAttributeId,InventoryItemAttributeId,InventoryItemId,ItemAttributeTypeId,AttributeValue,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboInventoryItemScrap" --source "[History].[dbo_InventoryItemScrap]" --fields.include "HistoryInventoryItemScrapId,InventoryItemScrapId,InventoryItemId,DefectId,UserId,Quantity,Comment,ScrapDate,ScrapDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboInventoryLocation" --source "[History].[dbo_InventoryLocation]" --fields.include "HistoryInventoryLocationId,InventoryLocationId,InventoryLocationTypeId,Name,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboOrder" --source "[History].[dbo_Order]" --fields.include "HistoryOrderId,OrderId,Number,OrderStateId,CustomerId,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboOrderItem" --source "[History].[dbo_OrderItem]" --fields.include "HistoryOrderItemId,OrderItemId,OrderId,FinishedPartId,Quantity,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboOrderItemAttribute" --source "[History].[dbo_OrderItemAttribute]" --fields.include "HistoryOrderItemAttributeId,OrderItemAttributeId,OrderItemId,ItemAttributeTypeId,AttributeValue,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboOrderItemUnit" --source "[History].[dbo_OrderItemUnit]" --fields.include "HistoryOrderItemUnitId,OrderItemUnitId,OrderItemId,PartId,SerialNumber,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboOrderItemUnitConsumption" --source "[History].[dbo_OrderItemUnitConsumption]" --fields.include "HistoryOrderItemUnitConsumptionId,OrderItemUnitConsumptionId,OrderItemUnitId,EquipmentId,UserId,BillOfProcessProcessWorkElementAttributeId,ConsumedSerialNumber,IsConsumed,ConsumedDate,ConsumedDateUtc,RemovedDate,RemovedDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboOrderItemUnitDataCollection" --source "[History].[dbo_OrderItemUnitDataCollection]" --fields.include "HistoryOrderItemUnitDataCollectionId,OrderItemUnitDataCollectionId,OrderItemUnitId,EquipmentId,UserId,BillOfProcessProcessWorkElementAttributeId,CollectedValue,CollectedDate,CollectedDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboOrderItemUnitScrap" --source "[History].[dbo_OrderItemUnitScrap]" --fields.include "HistoryOrderItemUnitScrapId,OrderItemUnitScrapId,OrderItemUnitId,EquipmentId,DefectId,UserId,Comment,ScrapDate,ScrapDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboOrderItemUnitWorkElementHistory" --source "[History].[dbo_OrderItemUnitWorkElementHistory]" --fields.include "HistoryOrderItemUnitWorkElementHistoryId,OrderItemUnitWorkElementHistoryId,OrderItemUnitId,BillOfProcessProcessWorkElementId,EquipmentId,WorkElementStatusId,UserId,StartDate,StartDateUtc,EndDate,EndDateUtc,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboPart" --source "[History].[dbo_Part]" --fields.include "HistoryPartId,PartId,PartTypeId,PartNumber,PartRevision,Description,UnitOfMeasureId,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboPartItemAttributeType" --source "[History].[dbo_PartItemAttributeType]" --fields.include "HistoryPartItemAttributeTypeId,PartItemAttributeTypeId,PartId,ItemAttributeTypeId,IsRequired,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboSupplier" --source "[History].[dbo_Supplier]" --fields.include "HistorySupplierId,SupplierId,Name,Address,PostalCode,City,StateOrProvince,Country,PhoneNumber,EmailAddress,ContactName,IsActive,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboWorkElementTypeAttribute" --source "[History].[dbo_WorkElementTypeAttribute]" --fields.include "HistoryWorkElementTypeAttributeId,WorkElementTypeAttributeId,WorkElementTypeId,Name,IsRequiredAtSetup,IsRequiredAtRun,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "DboWorkElementTypeAttributeListItem" --source "[History].[dbo_WorkElementTypeAttributeListItem]" --fields.include "HistoryWorkElementTypeAttributeListItemId,WorkElementTypeAttributeListItemId,WorkElementTypeAttributeId,Name,Description,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "EquipmentStateChange" --source "[History].[Equipment_StateChange]" --fields.include "HistoryStateChangeId,StateChangeId,EquipmentId,EquipmentName,StateChangeTime,StateChangeTimeUTC,CurrentStateId,PreviousStateId,PreviousStateTimeInSeconds,LastModifiedBy,LastModifiedTime,LastModifiedTimeUTC,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "GlobalCoater" --source "[History].[Global_Coater]" --fields.include "HistoryCoaterId,CoaterId,EquipmentId,Number,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "GlobalEquipment" --source "[History].[Global_Equipment]" --fields.include "HistoryEquipmentId,EquipmentId,LineId,ProcessId,Name,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "GlobalLine" --source "[History].[Global_Line]" --fields.include "HistoryLineId,LineId,UnitId,Name,DisplayName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "GlobalPlant" --source "[History].[Global_Plant]" --fields.include "HistoryPlantId,PlantId,SiteId,Name,DisplayName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "GlobalProcess" --source "[History].[Global_Process]" --fields.include "HistoryProcessId,ProcessId,Number,Name,LoopNumber,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "GlobalSite" --source "[History].[Global_Site]" --fields.include "HistorySiteId,SiteId,Name,DisplayName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
dab add "GlobalUnit" --source "[History].[Global_Unit]" --fields.include "HistoryUnitId,UnitId,PlantId,Name,DisplayName,LastModifiedBy,LastModifiedTime,LastModifiedTimeUtc,HistoryAction,HistoryActionBy,HistoryActionTimeUtc" --permissions "anonymous:*" 
@echo Adding views and tables without primary key
@echo Adding relationships
dab update UserAttribute --relationship User --target.entity User --cardinality one
dab update User --relationship UserAttribute --target.entity UserAttribute --cardinality many
dab update UserAttribute --relationship UserAttributeType --target.entity UserAttributeType --cardinality one
dab update UserAttributeType --relationship UserAttribute --target.entity UserAttribute --cardinality many
dab update UserRole --relationship Role --target.entity Role --cardinality one
dab update Role --relationship UserRole --target.entity UserRole --cardinality many
dab update UserRole --relationship User --target.entity User --cardinality one
dab update User --relationship UserRole --target.entity UserRole --cardinality many
dab update BillOfMaterial --relationship Part --target.entity Part --cardinality one
dab update Part --relationship BillOfMaterial --target.entity BillOfMaterial --cardinality many
dab update BillOfMaterialPart --relationship BillOfMaterial --target.entity BillOfMaterial --cardinality one
dab update BillOfMaterial --relationship BillOfMaterialPart --target.entity BillOfMaterialPart --cardinality many
dab update BillOfMaterialPart --relationship Part --target.entity Part --cardinality one
dab update Part --relationship BillOfMaterialPart --target.entity BillOfMaterialPart --cardinality many
dab update BillOfProcess --relationship Part --target.entity Part --cardinality one
dab update Part --relationship BillOfProcess --target.entity BillOfProcess --cardinality many
dab update BillOfProcessProcess --relationship BillOfProcess --target.entity BillOfProcess --cardinality one
dab update BillOfProcess --relationship BillOfProcessProcess --target.entity BillOfProcessProcess --cardinality many
dab update BillOfProcessProcess --relationship Process --target.entity Process --cardinality one
dab update Process --relationship BillOfProcessProcess --target.entity BillOfProcessProcess --cardinality many
dab update BillOfProcessProcessWorkElement --relationship BillOfProcessProcess --target.entity BillOfProcessProcess --cardinality one
dab update BillOfProcessProcess --relationship BillOfProcessProcessWorkElement --target.entity BillOfProcessProcessWorkElement --cardinality many
dab update BillOfProcessProcessWorkElement --relationship WorkElementType --target.entity WorkElementType --cardinality one
dab update WorkElementType --relationship BillOfProcessProcessWorkElement --target.entity BillOfProcessProcessWorkElement --cardinality many
dab update BillOfProcessProcessWorkElementAttribute --relationship BillOfProcessProcessWorkElement --target.entity BillOfProcessProcessWorkElement --cardinality one
dab update BillOfProcessProcessWorkElement --relationship BillOfProcessProcessWorkElementAttribute --target.entity BillOfProcessProcessWorkElementAttribute --cardinality many
dab update BillOfProcessProcessWorkElementAttribute --relationship WorkElementTypeAttribute --target.entity WorkElementTypeAttribute --cardinality one
dab update WorkElementTypeAttribute --relationship BillOfProcessProcessWorkElementAttribute --target.entity BillOfProcessProcessWorkElementAttribute --cardinality many
dab update Container --relationship ContainerType --target.entity ContainerType --cardinality one
dab update ContainerType --relationship Container --target.entity Container --cardinality many
dab update Container --relationship InventoryLocation --target.entity InventoryLocation --cardinality one
dab update InventoryLocation --relationship Container --target.entity Container --cardinality many
dab update ContainerOrderItemUnit --relationship Container --target.entity Container --cardinality one
dab update Container --relationship ContainerOrderItemUnit --target.entity ContainerOrderItemUnit --cardinality many
dab update ContainerOrderItemUnit --relationship OrderItemUnit --target.entity OrderItemUnit --cardinality one
dab update OrderItemUnit --relationship ContainerOrderItemUnit --target.entity ContainerOrderItemUnit --cardinality many
dab update Defect --relationship DefectCategory --target.entity DefectCategory --cardinality one
dab update DefectCategory --relationship Defect --target.entity Defect --cardinality many
dab update DefectProcess --relationship Defect --target.entity Defect --cardinality one
dab update Defect --relationship DefectProcess --target.entity DefectProcess --cardinality many
dab update DefectProcess --relationship Process --target.entity Process --cardinality one
dab update Process --relationship DefectProcess --target.entity DefectProcess --cardinality many
dab update FinishedGood --relationship Container --target.entity Container --cardinality one
dab update Container --relationship FinishedGood --target.entity FinishedGood --cardinality many
dab update InventoryItem --relationship InventoryItemType --target.entity InventoryItemType --cardinality one
dab update InventoryItemType --relationship InventoryItem --target.entity InventoryItem --cardinality many
dab update InventoryItem --relationship InventoryLocation --target.entity InventoryLocation --cardinality one
dab update InventoryLocation --relationship InventoryItem --target.entity InventoryItem --cardinality many
dab update InventoryItem --relationship Part --target.entity Part --cardinality one
dab update Part --relationship InventoryItem --target.entity InventoryItem --cardinality many
dab update InventoryItem --relationship Supplier --target.entity Supplier --cardinality one
dab update Supplier --relationship InventoryItem --target.entity InventoryItem --cardinality many
dab update InventoryItemAttribute --relationship InventoryItem --target.entity InventoryItem --cardinality one
dab update InventoryItem --relationship InventoryItemAttribute --target.entity InventoryItemAttribute --cardinality many
dab update InventoryItemAttribute --relationship ItemAttributeType --target.entity ItemAttributeType --cardinality one
dab update ItemAttributeType --relationship InventoryItemAttribute --target.entity InventoryItemAttribute --cardinality many
dab update InventoryItemScrap --relationship Defect --target.entity Defect --cardinality one
dab update Defect --relationship InventoryItemScrap --target.entity InventoryItemScrap --cardinality many
dab update InventoryItemScrap --relationship InventoryItem --target.entity InventoryItem --cardinality one
dab update InventoryItem --relationship InventoryItemScrap --target.entity InventoryItemScrap --cardinality many
dab update InventoryItemScrap --relationship User --target.entity User --cardinality one
dab update User --relationship InventoryItemScrap --target.entity InventoryItemScrap --cardinality many
dab update InventoryLocation --relationship InventoryLocationType --target.entity InventoryLocationType --cardinality one
dab update InventoryLocationType --relationship InventoryLocation --target.entity InventoryLocation --cardinality many
dab update Order --relationship Customer --target.entity Customer --cardinality one
dab update Customer --relationship Order --target.entity Order --cardinality many
dab update Order --relationship OrderState --target.entity OrderState --cardinality one
dab update OrderState --relationship Order --target.entity Order --cardinality many
dab update OrderItem --relationship Order --target.entity Order --cardinality one
dab update Order --relationship OrderItem --target.entity OrderItem --cardinality many
dab update OrderItem --relationship Part --target.entity Part --cardinality one
dab update Part --relationship OrderItem --target.entity OrderItem --cardinality many
dab update OrderItemAttribute --relationship ItemAttributeType --target.entity ItemAttributeType --cardinality one
dab update ItemAttributeType --relationship OrderItemAttribute --target.entity OrderItemAttribute --cardinality many
dab update OrderItemAttribute --relationship OrderItem --target.entity OrderItem --cardinality one
dab update OrderItem --relationship OrderItemAttribute --target.entity OrderItemAttribute --cardinality many
dab update OrderItemUnit --relationship OrderItem --target.entity OrderItem --cardinality one
dab update OrderItem --relationship OrderItemUnit --target.entity OrderItemUnit --cardinality many
dab update OrderItemUnit --relationship Part --target.entity Part --cardinality one
dab update Part --relationship OrderItemUnit --target.entity OrderItemUnit --cardinality many
dab update OrderItemUnitConsumption --relationship User --target.entity User --cardinality one
dab update User --relationship OrderItemUnitConsumption --target.entity OrderItemUnitConsumption --cardinality many
dab update OrderItemUnitConsumption --relationship BillOfProcessProcessWorkElementAttribute --target.entity BillOfProcessProcessWorkElementAttribute --cardinality one
dab update BillOfProcessProcessWorkElementAttribute --relationship OrderItemUnitConsumption --target.entity OrderItemUnitConsumption --cardinality many
dab update OrderItemUnitConsumption --relationship Equipment --target.entity Equipment --cardinality one
dab update Equipment --relationship OrderItemUnitConsumption --target.entity OrderItemUnitConsumption --cardinality many
dab update OrderItemUnitConsumption --relationship OrderItemUnit --target.entity OrderItemUnit --cardinality one
dab update OrderItemUnit --relationship OrderItemUnitConsumption --target.entity OrderItemUnitConsumption --cardinality many
dab update OrderItemUnitDataCollection --relationship User --target.entity User --cardinality one
dab update User --relationship OrderItemUnitDataCollection --target.entity OrderItemUnitDataCollection --cardinality many
dab update OrderItemUnitDataCollection --relationship BillOfProcessProcessWorkElementAttribute --target.entity BillOfProcessProcessWorkElementAttribute --cardinality one
dab update BillOfProcessProcessWorkElementAttribute --relationship OrderItemUnitDataCollection --target.entity OrderItemUnitDataCollection --cardinality many
dab update OrderItemUnitDataCollection --relationship Equipment --target.entity Equipment --cardinality one
dab update Equipment --relationship OrderItemUnitDataCollection --target.entity OrderItemUnitDataCollection --cardinality many
dab update OrderItemUnitDataCollection --relationship OrderItemUnit --target.entity OrderItemUnit --cardinality one
dab update OrderItemUnit --relationship OrderItemUnitDataCollection --target.entity OrderItemUnitDataCollection --cardinality many
dab update OrderItemUnitScrap --relationship Defect --target.entity Defect --cardinality one
dab update Defect --relationship OrderItemUnitScrap --target.entity OrderItemUnitScrap --cardinality many
dab update OrderItemUnitScrap --relationship Equipment --target.entity Equipment --cardinality one
dab update Equipment --relationship OrderItemUnitScrap --target.entity OrderItemUnitScrap --cardinality many
dab update OrderItemUnitScrap --relationship OrderItemUnit --target.entity OrderItemUnit --cardinality one
dab update OrderItemUnit --relationship OrderItemUnitScrap --target.entity OrderItemUnitScrap --cardinality many
dab update OrderItemUnitScrap --relationship User --target.entity User --cardinality one
dab update User --relationship OrderItemUnitScrap --target.entity OrderItemUnitScrap --cardinality many
dab update OrderItemUnitWorkElementHistory --relationship User --target.entity User --cardinality one
dab update User --relationship OrderItemUnitWorkElementHistory --target.entity OrderItemUnitWorkElementHistory --cardinality many
dab update OrderItemUnitWorkElementHistory --relationship BillOfProcessProcessWorkElement --target.entity BillOfProcessProcessWorkElement --cardinality one
dab update BillOfProcessProcessWorkElement --relationship OrderItemUnitWorkElementHistory --target.entity OrderItemUnitWorkElementHistory --cardinality many
dab update OrderItemUnitWorkElementHistory --relationship Equipment --target.entity Equipment --cardinality one
dab update Equipment --relationship OrderItemUnitWorkElementHistory --target.entity OrderItemUnitWorkElementHistory --cardinality many
dab update OrderItemUnitWorkElementHistory --relationship OrderItemUnit --target.entity OrderItemUnit --cardinality one
dab update OrderItemUnit --relationship OrderItemUnitWorkElementHistory --target.entity OrderItemUnitWorkElementHistory --cardinality many
dab update OrderItemUnitWorkElementHistory --relationship WorkElementStatus --target.entity WorkElementStatus --cardinality one
dab update WorkElementStatus --relationship OrderItemUnitWorkElementHistory --target.entity OrderItemUnitWorkElementHistory --cardinality many
dab update Part --relationship PartType --target.entity PartType --cardinality one
dab update PartType --relationship Part --target.entity Part --cardinality many
dab update Part --relationship UnitOfMeasure --target.entity UnitOfMeasure --cardinality one
dab update UnitOfMeasure --relationship Part --target.entity Part --cardinality many
dab update PartItemAttributeType --relationship ItemAttributeType --target.entity ItemAttributeType --cardinality one
dab update ItemAttributeType --relationship PartItemAttributeType --target.entity PartItemAttributeType --cardinality many
dab update PartItemAttributeType --relationship Part --target.entity Part --cardinality one
dab update Part --relationship PartItemAttributeType --target.entity PartItemAttributeType --cardinality many
dab update WorkElementTypeAttribute --relationship WorkElementType --target.entity WorkElementType --cardinality one
dab update WorkElementType --relationship WorkElementTypeAttribute --target.entity WorkElementTypeAttribute --cardinality many
dab update WorkElementTypeAttributeListItem --relationship WorkElementTypeAttribute --target.entity WorkElementTypeAttribute --cardinality one
dab update WorkElementTypeAttribute --relationship WorkElementTypeAttributeListItem --target.entity WorkElementTypeAttributeListItem --cardinality many
dab update StateChange --relationship State --target.entity State --cardinality one
dab update State --relationship StateChange --target.entity StateChange --cardinality many
dab update StateChange --relationship State --target.entity State --cardinality one
dab update State --relationship StateChange --target.entity StateChange --cardinality many
dab update Coater --relationship Equipment --target.entity Equipment --cardinality one
dab update Equipment --relationship Coater --target.entity Coater --cardinality many
dab update Equipment --relationship Line --target.entity Line --cardinality one
dab update Line --relationship Equipment --target.entity Equipment --cardinality many
dab update Equipment --relationship Process --target.entity Process --cardinality one
dab update Process --relationship Equipment --target.entity Equipment --cardinality many
dab update Line --relationship Unit --target.entity Unit --cardinality one
dab update Unit --relationship Line --target.entity Line --cardinality many
dab update Plant --relationship Site --target.entity Site --cardinality one
dab update Site --relationship Plant --target.entity Plant --cardinality many
dab update Unit --relationship Plant --target.entity Plant --cardinality one
dab update Plant --relationship Unit --target.entity Unit --cardinality many
@echo Adding stored procedures
@echo **
@echo ** run 'dab validate' to validate your configuration **
@echo ** run 'dab start' to start the development API host **
