// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class BillOfProcess
{
    public int BillOfProcessId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int PartId { get; set; }

    public DateTime EffectiveStartDate { get; set; }

    public DateTime EffectiveStartDateUtc { get; set; }

    public DateTime? EffectiveEndDate { get; set; }

    public DateTime? EffectiveEndDateUtc { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<BillOfProcessProcess> BillOfProcessProcesses { get; set; } = new List<BillOfProcessProcess>();

    public virtual Part Part { get; set; }
}