// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class BillOfProcessProcess
{
    public int BillOfProcessProcessId { get; set; }

    public int BillOfProcessId { get; set; }

    public int ProcessId { get; set; }

    public int Sequence { get; set; }

    public bool IsActive { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual BillOfProcess BillOfProcess { get; set; }

    public virtual ICollection<BillOfProcessProcessWorkElement> BillOfProcessProcessWorkElements { get; set; } = new List<BillOfProcessProcessWorkElement>();

    public virtual Process Process { get; set; }
}