// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class BillOfProcessProcessWorkElementAttribute
{
    public int BillOfProcessProcessWorkElementAttributeId { get; set; }

    public int BillOfProcessProcessWorkElementId { get; set; }

    public int WorkElementTypeAttributeId { get; set; }

    public string AttributeValue { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual BillOfProcessProcessWorkElement BillOfProcessProcessWorkElement { get; set; }

    public virtual ICollection<OrderItemUnitConsumption> OrderItemUnitConsumptions { get; set; } = new List<OrderItemUnitConsumption>();

    public virtual ICollection<OrderItemUnitDataCollection> OrderItemUnitDataCollections { get; set; } = new List<OrderItemUnitDataCollection>();

    public virtual WorkElementTypeAttribute WorkElementTypeAttribute { get; set; }
}