// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class BillOfMaterialPart
{
    public int BillOfMaterialPartId { get; set; }

    public int BillOfMaterialId { get; set; }

    public int PartId { get; set; }

    public decimal Quantity { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual BillOfMaterial BillOfMaterial { get; set; }

    public virtual Part Part { get; set; }
}