// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class BillOfProcessProcessWorkElement
{
    public int BillOfProcessProcessWorkElementId { get; set; }

    public int BillOfProcessProcessId { get; set; }

    public int WorkElementTypeId { get; set; }

    public string Name { get; set; }

    public int Sequence { get; set; }

    public bool IsRequired { get; set; }

    public bool IsActive { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual BillOfProcessProcess BillOfProcessProcess { get; set; }

    public virtual ICollection<BillOfProcessProcessWorkElementAttribute> BillOfProcessProcessWorkElementAttributes { get; set; } = new List<BillOfProcessProcessWorkElementAttribute>();

    public virtual ICollection<OrderItemUnitWorkElementHistory> OrderItemUnitWorkElementHistories { get; set; } = new List<OrderItemUnitWorkElementHistory>();

    public virtual WorkElementType WorkElementType { get; set; }
}