// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Container
{
    public long ContainerId { get; set; }

    public int ContainerTypeId { get; set; }

    public int InventoryLocationId { get; set; }

    public string SerialNumber { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<ContainerOrderItemUnit> ContainerOrderItemUnits { get; set; } = new List<ContainerOrderItemUnit>();

    public virtual ContainerType ContainerType { get; set; }

    public virtual ICollection<FinishedGood> FinishedGoods { get; set; } = new List<FinishedGood>();

    public virtual InventoryLocation InventoryLocation { get; set; }
}