// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class ContainerOrderItemUnit
{
    public long ContainerOrderItemUnitId { get; set; }

    public long ContainerId { get; set; }

    public long OrderItemUnitId { get; set; }

    public string PositionOnContainer { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual Container Container { get; set; }

    public virtual OrderItemUnit OrderItemUnit { get; set; }
}