// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string PostalCode { get; set; }

    public string City { get; set; }

    public string StateOrProvince { get; set; }

    public string Country { get; set; }

    public string PhoneNumber { get; set; }

    public string EmailAddress { get; set; }

    public string ContactName { get; set; }

    public bool IsActive { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}