// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class DefectProcess
{
    public int DefectProcessId { get; set; }

    public int DefectId { get; set; }

    public int ProcessId { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual Defect Defect { get; set; }

    public virtual Process Process { get; set; }
}