// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Defect
{
    public int DefectId { get; set; }

    public int DefectCategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public bool IsReworkable { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual DefectCategory DefectCategory { get; set; }

    public virtual ICollection<DefectProcess> DefectProcesses { get; set; } = new List<DefectProcess>();

    public virtual ICollection<InventoryItemScrap> InventoryItemScraps { get; set; } = new List<InventoryItemScrap>();

    public virtual ICollection<OrderItemUnitScrap> OrderItemUnitScraps { get; set; } = new List<OrderItemUnitScrap>();
}