// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Equipment
{
    public int EquipmentId { get; set; }

    public int LineId { get; set; }

    public int ProcessId { get; set; }

    public string Name { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<Coater> Coaters { get; set; } = new List<Coater>();

    public virtual Line Line { get; set; }

    public virtual ICollection<OrderItemUnitConsumption> OrderItemUnitConsumptions { get; set; } = new List<OrderItemUnitConsumption>();

    public virtual ICollection<OrderItemUnitDataCollection> OrderItemUnitDataCollections { get; set; } = new List<OrderItemUnitDataCollection>();

    public virtual ICollection<OrderItemUnitScrap> OrderItemUnitScraps { get; set; } = new List<OrderItemUnitScrap>();

    public virtual ICollection<OrderItemUnitWorkElementHistory> OrderItemUnitWorkElementHistories { get; set; } = new List<OrderItemUnitWorkElementHistory>();

    public virtual Process Process { get; set; }
}