// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class FinishedGood
{
    public long FinishedGoodsId { get; set; }

    public long ContainerId { get; set; }

    public int ContainerQuantityAtTransactionDate { get; set; }

    public bool IsReturnedToProduction { get; set; }

    public DateTime TransactionDate { get; set; }

    public DateTime TransactionDateUtc { get; set; }

    public DateTime? ReturnToProductionDate { get; set; }

    public DateTime? ReturnToProductionDateUtc { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual Container Container { get; set; }
}