// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class InventoryItem
{
    public long InventoryItemId { get; set; }

    public int InventoryItemTypeId { get; set; }

    public int InventoryLocationId { get; set; }

    public int PartId { get; set; }

    public int SupplierId { get; set; }

    public string SerialNumber { get; set; }

    public decimal Quantity { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<InventoryItemAttribute> InventoryItemAttributes { get; set; } = new List<InventoryItemAttribute>();

    public virtual ICollection<InventoryItemScrap> InventoryItemScraps { get; set; } = new List<InventoryItemScrap>();

    public virtual InventoryItemType InventoryItemType { get; set; }

    public virtual InventoryLocation InventoryLocation { get; set; }

    public virtual Part Part { get; set; }

    public virtual Supplier Supplier { get; set; }
}