// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class InventoryItemAttribute
{
    public int InventoryItemAttributeId { get; set; }

    public long InventoryItemId { get; set; }

    public int ItemAttributeTypeId { get; set; }

    public string AttributeValue { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual InventoryItem InventoryItem { get; set; }

    public virtual ItemAttributeType ItemAttributeType { get; set; }
}