// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class ItemAttributeType
{
    public int ItemAttributeTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<InventoryItemAttribute> InventoryItemAttributes { get; set; } = new List<InventoryItemAttribute>();

    public virtual ICollection<OrderItemAttribute> OrderItemAttributes { get; set; } = new List<OrderItemAttribute>();

    public virtual ICollection<PartItemAttributeType> PartItemAttributeTypes { get; set; } = new List<PartItemAttributeType>();
}