// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Line
{
    public int LineId { get; set; }

    public int UnitId { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<Equipment> Equipment { get; set; } = new List<Equipment>();

    public virtual Unit Unit { get; set; }
}