// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ue_mes_data.Model;

public partial class MesProductionContext : DbContext
{
    public MesProductionContext(DbContextOptions<MesProductionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BillOfMaterial> BillOfMaterials { get; set; }

    public virtual DbSet<BillOfMaterialPart> BillOfMaterialParts { get; set; }

    public virtual DbSet<BillOfProcess> BillOfProcesses { get; set; }

    public virtual DbSet<BillOfProcessProcess> BillOfProcessProcesses { get; set; }

    public virtual DbSet<BillOfProcessProcessWorkElement> BillOfProcessProcessWorkElements { get; set; }

    public virtual DbSet<BillOfProcessProcessWorkElementAttribute> BillOfProcessProcessWorkElementAttributes { get; set; }

    public virtual DbSet<Coater> Coaters { get; set; }

    public virtual DbSet<Container> Containers { get; set; }

    public virtual DbSet<ContainerOrderItemUnit> ContainerOrderItemUnits { get; set; }

    public virtual DbSet<ContainerType> ContainerTypes { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Defect> Defects { get; set; }

    public virtual DbSet<DefectCategory> DefectCategories { get; set; }

    public virtual DbSet<DefectProcess> DefectProcesses { get; set; }

    public virtual DbSet<Equipment> Equipment { get; set; }

    public virtual DbSet<FinishedGood> FinishedGoods { get; set; }

    public virtual DbSet<InventoryItem> InventoryItems { get; set; }

    public virtual DbSet<InventoryItemAttribute> InventoryItemAttributes { get; set; }

    public virtual DbSet<InventoryItemScrap> InventoryItemScraps { get; set; }

    public virtual DbSet<InventoryItemType> InventoryItemTypes { get; set; }

    public virtual DbSet<InventoryLocation> InventoryLocations { get; set; }

    public virtual DbSet<InventoryLocationType> InventoryLocationTypes { get; set; }

    public virtual DbSet<ItemAttributeType> ItemAttributeTypes { get; set; }

    public virtual DbSet<Line> Lines { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<OrderItemAttribute> OrderItemAttributes { get; set; }

    public virtual DbSet<OrderItemUnit> OrderItemUnits { get; set; }

    public virtual DbSet<OrderItemUnitConsumption> OrderItemUnitConsumptions { get; set; }

    public virtual DbSet<OrderItemUnitDataCollection> OrderItemUnitDataCollections { get; set; }

    public virtual DbSet<OrderItemUnitScrap> OrderItemUnitScraps { get; set; }

    public virtual DbSet<OrderItemUnitWorkElementHistory> OrderItemUnitWorkElementHistories { get; set; }

    public virtual DbSet<OrderState> OrderStates { get; set; }

    public virtual DbSet<Part> Parts { get; set; }

    public virtual DbSet<PartItemAttributeType> PartItemAttributeTypes { get; set; }

    public virtual DbSet<PartType> PartTypes { get; set; }

    public virtual DbSet<Plant> Plants { get; set; }

    public virtual DbSet<Process> Processes { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Site> Sites { get; set; }

    public virtual DbSet<State> States { get; set; }

    public virtual DbSet<StateChange> StateChanges { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAttribute> UserAttributes { get; set; }

    public virtual DbSet<UserAttributeType> UserAttributeTypes { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<WorkElementStatus> WorkElementStatuses { get; set; }

    public virtual DbSet<WorkElementType> WorkElementTypes { get; set; }

    public virtual DbSet<WorkElementTypeAttribute> WorkElementTypeAttributes { get; set; }

    public virtual DbSet<WorkElementTypeAttributeListItem> WorkElementTypeAttributeListItems { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BillOfMaterial>(entity =>
        {
            entity.ToTable("BillOfMaterial", tb => tb.HasTrigger("BillOfMaterial_History"));

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Part).WithMany(p => p.BillOfMaterials)
                .HasForeignKey(d => d.PartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfMaterial_Part");
        });

        modelBuilder.Entity<BillOfMaterialPart>(entity =>
        {
            entity.ToTable("BillOfMaterialPart", tb => tb.HasTrigger("BillOfMaterialPart_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Quantity).HasColumnType("decimal(9, 2)");

            entity.HasOne(d => d.BillOfMaterial).WithMany(p => p.BillOfMaterialParts)
                .HasForeignKey(d => d.BillOfMaterialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfMaterialPart_BillOfMaterial");

            entity.HasOne(d => d.Part).WithMany(p => p.BillOfMaterialParts)
                .HasForeignKey(d => d.PartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfMaterialPart_Part");
        });

        modelBuilder.Entity<BillOfProcess>(entity =>
        {
            entity.ToTable("BillOfProcess", tb => tb.HasTrigger("BillOfProcess_History"));

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Part).WithMany(p => p.BillOfProcesses)
                .HasForeignKey(d => d.PartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfProcess_Part");
        });

        modelBuilder.Entity<BillOfProcessProcess>(entity =>
        {
            entity.ToTable("BillOfProcessProcess", tb => tb.HasTrigger("BillOfProcessProcess_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.BillOfProcess).WithMany(p => p.BillOfProcessProcesses)
                .HasForeignKey(d => d.BillOfProcessId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfProcessProcess_BillOfProcess");

            entity.HasOne(d => d.Process).WithMany(p => p.BillOfProcessProcesses)
                .HasForeignKey(d => d.ProcessId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfProcessProcess_Process");
        });

        modelBuilder.Entity<BillOfProcessProcessWorkElement>(entity =>
        {
            entity.ToTable("BillOfProcessProcessWorkElement", tb => tb.HasTrigger("BillOfProcessProcessWorkElement_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.BillOfProcessProcess).WithMany(p => p.BillOfProcessProcessWorkElements)
                .HasForeignKey(d => d.BillOfProcessProcessId)
                .HasConstraintName("FK_BillOfProcessProcessWorkElement_BillOfProcessProcess");

            entity.HasOne(d => d.WorkElementType).WithMany(p => p.BillOfProcessProcessWorkElements)
                .HasForeignKey(d => d.WorkElementTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfProcessProcessWorkElement_WorkElementType");
        });

        modelBuilder.Entity<BillOfProcessProcessWorkElementAttribute>(entity =>
        {
            entity.ToTable("BillOfProcessProcessWorkElementAttribute", tb => tb.HasTrigger("BillOfProcessProcessWorkElementAttribute_History"));

            entity.Property(e => e.AttributeValue)
                .IsRequired()
                .HasMaxLength(4000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.BillOfProcessProcessWorkElement).WithMany(p => p.BillOfProcessProcessWorkElementAttributes)
                .HasForeignKey(d => d.BillOfProcessProcessWorkElementId)
                .HasConstraintName("FK_BillOfProcessProcessWorkElementAttribute_BillOfProcessProcessWorkElement");

            entity.HasOne(d => d.WorkElementTypeAttribute).WithMany(p => p.BillOfProcessProcessWorkElementAttributes)
                .HasForeignKey(d => d.WorkElementTypeAttributeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillOfProcessProcessWorkElementAttribute_WorkElementTypeAttribute");
        });

        modelBuilder.Entity<Coater>(entity =>
        {
            entity.ToTable("Coater", "Global", tb => tb.HasTrigger("Coater_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Equipment).WithMany(p => p.Coaters)
                .HasForeignKey(d => d.EquipmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Coater_Equipment");
        });

        modelBuilder.Entity<Container>(entity =>
        {
            entity.ToTable("Container", tb => tb.HasTrigger("Container_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.SerialNumber)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ContainerType).WithMany(p => p.Containers)
                .HasForeignKey(d => d.ContainerTypeId)
                .HasConstraintName("FK_Container_ContainerType");

            entity.HasOne(d => d.InventoryLocation).WithMany(p => p.Containers)
                .HasForeignKey(d => d.InventoryLocationId)
                .HasConstraintName("FK_Container_InventoryLocation");
        });

        modelBuilder.Entity<ContainerOrderItemUnit>(entity =>
        {
            entity.ToTable("ContainerOrderItemUnit", tb => tb.HasTrigger("ContainerOrderItemUnit_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PositionOnContainer)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Container).WithMany(p => p.ContainerOrderItemUnits)
                .HasForeignKey(d => d.ContainerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContainerOrderItemUnit_Container");

            entity.HasOne(d => d.OrderItemUnit).WithMany(p => p.ContainerOrderItemUnits)
                .HasForeignKey(d => d.OrderItemUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ContainerOrderItemUnit_OrderItemUnit");
        });

        modelBuilder.Entity<ContainerType>(entity =>
        {
            entity.ToTable("ContainerType");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customer", tb => tb.HasTrigger("Customer_History"));

            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(600)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ContactName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmailAddress)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PostalCode)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.StateOrProvince)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Defect>(entity =>
        {
            entity.ToTable("Defect", tb => tb.HasTrigger("Defect_History"));

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.DefectCategory).WithMany(p => p.Defects)
                .HasForeignKey(d => d.DefectCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Defect_DefectCategory");
        });

        modelBuilder.Entity<DefectCategory>(entity =>
        {
            entity.ToTable("DefectCategory", tb => tb.HasTrigger("DefectCategory_History"));

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DefectProcess>(entity =>
        {
            entity.ToTable("DefectProcess", tb => tb.HasTrigger("DefectProcess_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Defect).WithMany(p => p.DefectProcesses)
                .HasForeignKey(d => d.DefectId)
                .HasConstraintName("FK_DefectProcess_Defect");

            entity.HasOne(d => d.Process).WithMany(p => p.DefectProcesses)
                .HasForeignKey(d => d.ProcessId)
                .HasConstraintName("FK_DefectProcess_Process");
        });

        modelBuilder.Entity<Equipment>(entity =>
        {
            entity.ToTable("Equipment", "Global", tb => tb.HasTrigger("Equipment_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false);

            entity.HasOne(d => d.Line).WithMany(p => p.Equipment)
                .HasForeignKey(d => d.LineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Equipment_Line");

            entity.HasOne(d => d.Process).WithMany(p => p.Equipment)
                .HasForeignKey(d => d.ProcessId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Equipment_Process");
        });

        modelBuilder.Entity<FinishedGood>(entity =>
        {
            entity.HasKey(e => e.FinishedGoodsId);

            entity.ToTable(tb => tb.HasTrigger("FinishedGoods_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Container).WithMany(p => p.FinishedGoods)
                .HasForeignKey(d => d.ContainerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FinishedGoods_Container");
        });

        modelBuilder.Entity<InventoryItem>(entity =>
        {
            entity.ToTable("InventoryItem", tb => tb.HasTrigger("InventoryItem_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Quantity).HasColumnType("decimal(9, 2)");
            entity.Property(e => e.SerialNumber)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.InventoryItemType).WithMany(p => p.InventoryItems)
                .HasForeignKey(d => d.InventoryItemTypeId)
                .HasConstraintName("FK_InventoryItem_InventoryItemType");

            entity.HasOne(d => d.InventoryLocation).WithMany(p => p.InventoryItems)
                .HasForeignKey(d => d.InventoryLocationId)
                .HasConstraintName("FK_InventoryItem_InventoryLocation");

            entity.HasOne(d => d.Part).WithMany(p => p.InventoryItems)
                .HasForeignKey(d => d.PartId)
                .HasConstraintName("FK_InventoryItem_Part");

            entity.HasOne(d => d.Supplier).WithMany(p => p.InventoryItems)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryItem_Supplier");
        });

        modelBuilder.Entity<InventoryItemAttribute>(entity =>
        {
            entity.ToTable("InventoryItemAttribute", tb => tb.HasTrigger("InventoryItemAttribute_History"));

            entity.Property(e => e.AttributeValue)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.InventoryItem).WithMany(p => p.InventoryItemAttributes)
                .HasForeignKey(d => d.InventoryItemId)
                .HasConstraintName("FK_InventoryItemAttribute_InventoryItem");

            entity.HasOne(d => d.ItemAttributeType).WithMany(p => p.InventoryItemAttributes)
                .HasForeignKey(d => d.ItemAttributeTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryItemAttribute_ItemAttributeType");
        });

        modelBuilder.Entity<InventoryItemScrap>(entity =>
        {
            entity.ToTable("InventoryItemScrap", tb => tb.HasTrigger("InventoryItemScrap_History"));

            entity.Property(e => e.Comment)
                .IsRequired()
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Quantity).HasColumnType("decimal(9, 2)");

            entity.HasOne(d => d.Defect).WithMany(p => p.InventoryItemScraps)
                .HasForeignKey(d => d.DefectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryItemScrap_Defect");

            entity.HasOne(d => d.InventoryItem).WithMany(p => p.InventoryItemScraps)
                .HasForeignKey(d => d.InventoryItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryItemScrap_InventoryItem");

            entity.HasOne(d => d.User).WithMany(p => p.InventoryItemScraps)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryItemScrap_User");
        });

        modelBuilder.Entity<InventoryItemType>(entity =>
        {
            entity.ToTable("InventoryItemType");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<InventoryLocation>(entity =>
        {
            entity.ToTable("InventoryLocation", tb => tb.HasTrigger("InventoryLocation_History"));

            entity.HasIndex(e => e.Name, "IX_InventoryLocation_Name").IsUnique();

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.InventoryLocationType).WithMany(p => p.InventoryLocations)
                .HasForeignKey(d => d.InventoryLocationTypeId)
                .HasConstraintName("FK_InventoryLocation_InventoryLocationType");
        });

        modelBuilder.Entity<InventoryLocationType>(entity =>
        {
            entity.ToTable("InventoryLocationType");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ItemAttributeType>(entity =>
        {
            entity.ToTable("ItemAttributeType");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Line>(entity =>
        {
            entity.ToTable("Line", "Global", tb => tb.HasTrigger("Line_History"));

            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Unit).WithMany(p => p.Lines)
                .HasForeignKey(d => d.UnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Line_Unit");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("Order", tb => tb.HasTrigger("Order_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_Customer");

            entity.HasOne(d => d.OrderState).WithMany(p => p.Orders)
                .HasForeignKey(d => d.OrderStateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_OrderState");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.ToTable("OrderItem", tb => tb.HasTrigger("OrderItem_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.FinishedPart).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.FinishedPartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItem_Part");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItem_Order");
        });

        modelBuilder.Entity<OrderItemAttribute>(entity =>
        {
            entity.ToTable("OrderItemAttribute", tb => tb.HasTrigger("OrderItemAttribute_History"));

            entity.Property(e => e.AttributeValue)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.ItemAttributeType).WithMany(p => p.OrderItemAttributes)
                .HasForeignKey(d => d.ItemAttributeTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemAttribute_ItemAttributeType");

            entity.HasOne(d => d.OrderItem).WithMany(p => p.OrderItemAttributes)
                .HasForeignKey(d => d.OrderItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemAttribute_OrderItem");
        });

        modelBuilder.Entity<OrderItemUnit>(entity =>
        {
            entity.ToTable("OrderItemUnit", tb => tb.HasTrigger("OrderItemUnit_History"));

            entity.HasIndex(e => e.SerialNumber, "IX_OrderItemUnit_SerialNumber").IsUnique();

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.SerialNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.OrderItem).WithMany(p => p.OrderItemUnits)
                .HasForeignKey(d => d.OrderItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnit_OrderItem");

            entity.HasOne(d => d.Part).WithMany(p => p.OrderItemUnits)
                .HasForeignKey(d => d.PartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnit_Part");
        });

        modelBuilder.Entity<OrderItemUnitConsumption>(entity =>
        {
            entity.ToTable("OrderItemUnitConsumption", tb => tb.HasTrigger("OrderItemUnitConsumption_History"));

            entity.Property(e => e.ConsumedSerialNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.BillOfProcessProcessWorkElementAttribute).WithMany(p => p.OrderItemUnitConsumptions)
                .HasForeignKey(d => d.BillOfProcessProcessWorkElementAttributeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitConsumption_BillOfProcessProcessWorkElementAttribute");

            entity.HasOne(d => d.Equipment).WithMany(p => p.OrderItemUnitConsumptions)
                .HasForeignKey(d => d.EquipmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitConsumption_GlobalEquipment");

            entity.HasOne(d => d.OrderItemUnit).WithMany(p => p.OrderItemUnitConsumptions)
                .HasForeignKey(d => d.OrderItemUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitConsumption_OrderItemUnit");

            entity.HasOne(d => d.User).WithMany(p => p.OrderItemUnitConsumptions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitConsumption_AuthorizationUser");
        });

        modelBuilder.Entity<OrderItemUnitDataCollection>(entity =>
        {
            entity.ToTable("OrderItemUnitDataCollection", tb => tb.HasTrigger("OrderItemUnitDataCollection_History"));

            entity.Property(e => e.CollectedValue)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.BillOfProcessProcessWorkElementAttribute).WithMany(p => p.OrderItemUnitDataCollections)
                .HasForeignKey(d => d.BillOfProcessProcessWorkElementAttributeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitDataCollection_BillOfProcessProcessWorkElementAttribute");

            entity.HasOne(d => d.Equipment).WithMany(p => p.OrderItemUnitDataCollections)
                .HasForeignKey(d => d.EquipmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitDataCollection_GlobalEquipment");

            entity.HasOne(d => d.OrderItemUnit).WithMany(p => p.OrderItemUnitDataCollections)
                .HasForeignKey(d => d.OrderItemUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitDataCollection_OrderItemUnit");

            entity.HasOne(d => d.User).WithMany(p => p.OrderItemUnitDataCollections)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitDataCollection_AuthorizationUser");
        });

        modelBuilder.Entity<OrderItemUnitScrap>(entity =>
        {
            entity.ToTable("OrderItemUnitScrap", tb => tb.HasTrigger("OrderItemUnitScrap_History"));

            entity.HasIndex(e => e.OrderItemUnitId, "IX_OrderItemUnitScrap_OrderItemUnitId").IsUnique();

            entity.Property(e => e.Comment)
                .IsRequired()
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Defect).WithMany(p => p.OrderItemUnitScraps)
                .HasForeignKey(d => d.DefectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitScrap_Defect");

            entity.HasOne(d => d.Equipment).WithMany(p => p.OrderItemUnitScraps)
                .HasForeignKey(d => d.EquipmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitScrap_Equipment");

            entity.HasOne(d => d.OrderItemUnit).WithOne(p => p.OrderItemUnitScrap)
                .HasForeignKey<OrderItemUnitScrap>(d => d.OrderItemUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitScrap_OrderItemUnit");

            entity.HasOne(d => d.User).WithMany(p => p.OrderItemUnitScraps)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitScrap_User");
        });

        modelBuilder.Entity<OrderItemUnitWorkElementHistory>(entity =>
        {
            entity.ToTable("OrderItemUnitWorkElementHistory", tb => tb.HasTrigger("OrderItemUnitWorkElementHistory_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.BillOfProcessProcessWorkElement).WithMany(p => p.OrderItemUnitWorkElementHistories)
                .HasForeignKey(d => d.BillOfProcessProcessWorkElementId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitWorkElementHistory_BillOfProcessProcessWorkElement");

            entity.HasOne(d => d.Equipment).WithMany(p => p.OrderItemUnitWorkElementHistories)
                .HasForeignKey(d => d.EquipmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitWorkElementHistory_GlobalEquipment");

            entity.HasOne(d => d.OrderItemUnit).WithMany(p => p.OrderItemUnitWorkElementHistories)
                .HasForeignKey(d => d.OrderItemUnitId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitWorkElementHistory_OrderItemUnit");

            entity.HasOne(d => d.User).WithMany(p => p.OrderItemUnitWorkElementHistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitWorkElementHistory_AuthorizationUser");

            entity.HasOne(d => d.WorkElementStatus).WithMany(p => p.OrderItemUnitWorkElementHistories)
                .HasForeignKey(d => d.WorkElementStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItemUnitWorkElementHistory_WorkElementStatus");
        });

        modelBuilder.Entity<OrderState>(entity =>
        {
            entity.ToTable("OrderState");

            entity.HasIndex(e => e.Name, "IX_OrderState_ShortName").IsUnique();

            entity.Property(e => e.OrderStateId).ValueGeneratedOnAdd();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Part>(entity =>
        {
            entity.ToTable("Part", tb => tb.HasTrigger("Part_History"));

            entity.HasIndex(e => new { e.PartNumber, e.PartRevision }, "IX_Part_PartNumber_PartRevision").IsUnique();

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.PartNumber)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PartRevision)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.PartType).WithMany(p => p.Parts)
                .HasForeignKey(d => d.PartTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Part_PartType");

            entity.HasOne(d => d.UnitOfMeasure).WithMany(p => p.Parts)
                .HasForeignKey(d => d.UnitOfMeasureId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Part_UnitOfMeasure");
        });

        modelBuilder.Entity<PartItemAttributeType>(entity =>
        {
            entity.ToTable("PartItemAttributeType", tb => tb.HasTrigger("PartItemAttributeType_History"));

            entity.HasIndex(e => new { e.PartId, e.ItemAttributeTypeId }, "UIX_PartItemAttributeType_PartId_ItemAttributeTypeId").IsUnique();

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.ItemAttributeType).WithMany(p => p.PartItemAttributeTypes)
                .HasForeignKey(d => d.ItemAttributeTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PartItemAttributeType_ItemAttributeType");

            entity.HasOne(d => d.Part).WithMany(p => p.PartItemAttributeTypes)
                .HasForeignKey(d => d.PartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PartItemAttributeType_Part");
        });

        modelBuilder.Entity<PartType>(entity =>
        {
            entity.ToTable("PartType");

            entity.Property(e => e.PartTypeId).ValueGeneratedOnAdd();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Plant>(entity =>
        {
            entity.ToTable("Plant", "Global", tb => tb.HasTrigger("Plant_History"));

            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Site).WithMany(p => p.Plants)
                .HasForeignKey(d => d.SiteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Plant_Site");
        });

        modelBuilder.Entity<Process>(entity =>
        {
            entity.ToTable("Process", "Global", tb => tb.HasTrigger("Process_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("Role", "Authorization");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Site>(entity =>
        {
            entity.ToTable("Site", "Global", tb => tb.HasTrigger("Site_History"));

            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<State>(entity =>
        {
            entity.ToTable("State", "Equipment");

            entity.Property(e => e.StateId).ValueGeneratedNever();
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ShortName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<StateChange>(entity =>
        {
            entity.ToTable("StateChange", "Equipment", tb => tb.HasTrigger("StateChange_History"));

            entity.Property(e => e.EquipmentName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("LastModifiedTimeUTC");
            entity.Property(e => e.StateChangeTimeUtc).HasColumnName("StateChangeTimeUTC");

            entity.HasOne(d => d.CurrentState).WithMany(p => p.StateChangeCurrentStates)
                .HasForeignKey(d => d.CurrentStateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StateChangeCurrent_State");

            entity.HasOne(d => d.PreviousState).WithMany(p => p.StateChangePreviousStates)
                .HasForeignKey(d => d.PreviousStateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StateChangePrevious_State");
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.ToTable("Supplier", tb => tb.HasTrigger("Supplier_History"));

            entity.Property(e => e.Address)
                .HasMaxLength(600)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ContactName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Country)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EmailAddress)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PostalCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.StateOrProvince)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.ToTable("Unit", "Global", tb => tb.HasTrigger("Unit_History"));

            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Plant).WithMany(p => p.Units)
                .HasForeignKey(d => d.PlantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Unit_Plant");
        });

        modelBuilder.Entity<UnitOfMeasure>(entity =>
        {
            entity.ToTable("UnitOfMeasure");

            entity.Property(e => e.UnitOfMeasureId).ValueGeneratedOnAdd();
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ShortName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User", "Authorization", tb => tb.HasTrigger("User_History"));

            entity.Property(e => e.EmailAddress)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.JobTitle)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LoginName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserAttribute>(entity =>
        {
            entity.ToTable("UserAttribute", "Authorization");

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.UserAttributeValue)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.HasOne(d => d.UserAttributeType).WithMany(p => p.UserAttributes)
                .HasForeignKey(d => d.UserAttributeTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAttribute_UserAttributeType");

            entity.HasOne(d => d.User).WithMany(p => p.UserAttributes)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserAttribute_User");
        });

        modelBuilder.Entity<UserAttributeType>(entity =>
        {
            entity.ToTable("UserAttributeType", "Authorization");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.ToTable("UserRole", "Authorization", tb => tb.HasTrigger("UserRole_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_Role");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRole_User");
        });

        modelBuilder.Entity<WorkElementStatus>(entity =>
        {
            entity.ToTable("WorkElementStatus");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WorkElementType>(entity =>
        {
            entity.ToTable("WorkElementType");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<WorkElementTypeAttribute>(entity =>
        {
            entity.ToTable("WorkElementTypeAttribute", tb => tb.HasTrigger("WorkElementTypeAttribute_History"));

            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.WorkElementType).WithMany(p => p.WorkElementTypeAttributes)
                .HasForeignKey(d => d.WorkElementTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkElementTypeAttribute_WorkElementType");
        });

        modelBuilder.Entity<WorkElementTypeAttributeListItem>(entity =>
        {
            entity.ToTable("WorkElementTypeAttributeListItem", tb => tb.HasTrigger("WorkElementTypeAttributeListItem_History"));

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.LastModifiedBy)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(suser_name())");
            entity.Property(e => e.LastModifiedTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastModifiedTimeUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.WorkElementTypeAttribute).WithMany(p => p.WorkElementTypeAttributeListItems)
                .HasForeignKey(d => d.WorkElementTypeAttributeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WorkElementTypeAttributeListItem_WorkElementTypeAttribute");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}