// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class OrderItemAttribute
{
    public int OrderItemAttributeId { get; set; }

    public int OrderItemId { get; set; }

    public int ItemAttributeTypeId { get; set; }

    public string AttributeValue { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ItemAttributeType ItemAttributeType { get; set; }

    public virtual OrderItem OrderItem { get; set; }
}