// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class OrderItemUnitWorkElementHistory
{
    public long OrderItemUnitWorkElementHistoryId { get; set; }

    public long OrderItemUnitId { get; set; }

    public int BillOfProcessProcessWorkElementId { get; set; }

    public int EquipmentId { get; set; }

    public int WorkElementStatusId { get; set; }

    public int UserId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime StartDateUtc { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? EndDateUtc { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual BillOfProcessProcessWorkElement BillOfProcessProcessWorkElement { get; set; }

    public virtual Equipment Equipment { get; set; }

    public virtual OrderItemUnit OrderItemUnit { get; set; }

    public virtual User User { get; set; }

    public virtual WorkElementStatus WorkElementStatus { get; set; }
}