// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class OrderItem
{
    public int OrderItemId { get; set; }

    public int OrderId { get; set; }

    public int FinishedPartId { get; set; }

    public int Quantity { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual Part FinishedPart { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderItemAttribute> OrderItemAttributes { get; set; } = new List<OrderItemAttribute>();

    public virtual ICollection<OrderItemUnit> OrderItemUnits { get; set; } = new List<OrderItemUnit>();
}