// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class OrderItemUnitConsumption
{
    public long OrderItemUnitConsumptionId { get; set; }

    public long OrderItemUnitId { get; set; }

    public int EquipmentId { get; set; }

    public int UserId { get; set; }

    public int BillOfProcessProcessWorkElementAttributeId { get; set; }

    public string ConsumedSerialNumber { get; set; }

    public bool IsConsumed { get; set; }

    public DateTime ConsumedDate { get; set; }

    public DateTime ConsumedDateUtc { get; set; }

    public DateTime? RemovedDate { get; set; }

    public DateTime? RemovedDateUtc { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual BillOfProcessProcessWorkElementAttribute BillOfProcessProcessWorkElementAttribute { get; set; }

    public virtual Equipment Equipment { get; set; }

    public virtual OrderItemUnit OrderItemUnit { get; set; }

    public virtual User User { get; set; }
}