// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class OrderItemUnitScrap
{
    public long OrderItemUnitScrapId { get; set; }

    public long OrderItemUnitId { get; set; }

    public int EquipmentId { get; set; }

    public int DefectId { get; set; }

    public int UserId { get; set; }

    public string Comment { get; set; }

    public DateTime ScrapDate { get; set; }

    public DateTime ScrapDateUtc { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual Defect Defect { get; set; }

    public virtual Equipment Equipment { get; set; }

    public virtual OrderItemUnit OrderItemUnit { get; set; }

    public virtual User User { get; set; }
}