// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class OrderItemUnit
{
    public long OrderItemUnitId { get; set; }

    public int OrderItemId { get; set; }

    public int PartId { get; set; }

    public string SerialNumber { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<ContainerOrderItemUnit> ContainerOrderItemUnits { get; set; } = new List<ContainerOrderItemUnit>();

    public virtual OrderItem OrderItem { get; set; }

    public virtual ICollection<OrderItemUnitConsumption> OrderItemUnitConsumptions { get; set; } = new List<OrderItemUnitConsumption>();

    public virtual ICollection<OrderItemUnitDataCollection> OrderItemUnitDataCollections { get; set; } = new List<OrderItemUnitDataCollection>();

    public virtual OrderItemUnitScrap OrderItemUnitScrap { get; set; }

    public virtual ICollection<OrderItemUnitWorkElementHistory> OrderItemUnitWorkElementHistories { get; set; } = new List<OrderItemUnitWorkElementHistory>();

    public virtual Part Part { get; set; }
}