// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class PartItemAttributeType
{
    public int PartItemAttributeTypeId { get; set; }

    public int PartId { get; set; }

    public int ItemAttributeTypeId { get; set; }

    public bool IsRequired { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ItemAttributeType ItemAttributeType { get; set; }

    public virtual Part Part { get; set; }
}