// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Part
{
    public int PartId { get; set; }

    public byte PartTypeId { get; set; }

    public string PartNumber { get; set; }

    public string PartRevision { get; set; }

    public string Description { get; set; }

    public byte UnitOfMeasureId { get; set; }

    public bool IsActive { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<BillOfMaterialPart> BillOfMaterialParts { get; set; } = new List<BillOfMaterialPart>();

    public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; } = new List<BillOfMaterial>();

    public virtual ICollection<BillOfProcess> BillOfProcesses { get; set; } = new List<BillOfProcess>();

    public virtual ICollection<InventoryItem> InventoryItems { get; set; } = new List<InventoryItem>();

    public virtual ICollection<OrderItemUnit> OrderItemUnits { get; set; } = new List<OrderItemUnit>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PartItemAttributeType> PartItemAttributeTypes { get; set; } = new List<PartItemAttributeType>();

    public virtual PartType PartType { get; set; }

    public virtual UnitOfMeasure UnitOfMeasure { get; set; }
}