// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Plant
{
    public int PlantId { get; set; }

    public int SiteId { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual Site Site { get; set; }

    public virtual ICollection<Unit> Units { get; set; } = new List<Unit>();
}