// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Process
{
    public int ProcessId { get; set; }

    public string Number { get; set; }

    public string Name { get; set; }

    public int? LoopNumber { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<BillOfProcessProcess> BillOfProcessProcesses { get; set; } = new List<BillOfProcessProcess>();

    public virtual ICollection<DefectProcess> DefectProcesses { get; set; } = new List<DefectProcess>();

    public virtual ICollection<Equipment> Equipment { get; set; } = new List<Equipment>();
}