// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class Site
{
    public int SiteId { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<Plant> Plants { get; set; } = new List<Plant>();
}