// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class State
{
    public int StateId { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<StateChange> StateChangeCurrentStates { get; set; } = new List<StateChange>();

    public virtual ICollection<StateChange> StateChangePreviousStates { get; set; } = new List<StateChange>();
}