// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class StateChange
{
    public long StateChangeId { get; set; }

    public long EquipmentId { get; set; }

    public string EquipmentName { get; set; }

    public DateTime StateChangeTime { get; set; }

    public DateTime StateChangeTimeUtc { get; set; }

    public int CurrentStateId { get; set; }

    public int PreviousStateId { get; set; }

    public int PreviousStateTimeInSeconds { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual State CurrentState { get; set; }

    public virtual State PreviousState { get; set; }
}