// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class UserRole
{
    public long UserRoleId { get; set; }

    public int UserId { get; set; }

    public int RoleId { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual Role Role { get; set; }

    public virtual User User { get; set; }
}