// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class UserAttribute
{
    public long UserAttributeId { get; set; }

    public int UserId { get; set; }

    public int UserAttributeTypeId { get; set; }

    public string UserAttributeValue { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual User User { get; set; }

    public virtual UserAttributeType UserAttributeType { get; set; }
}