// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class User
{
    public int UserId { get; set; }

    public string LoginName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string EmailAddress { get; set; }

    public string JobTitle { get; set; }

    public bool IsActive { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<InventoryItemScrap> InventoryItemScraps { get; set; } = new List<InventoryItemScrap>();

    public virtual ICollection<OrderItemUnitConsumption> OrderItemUnitConsumptions { get; set; } = new List<OrderItemUnitConsumption>();

    public virtual ICollection<OrderItemUnitDataCollection> OrderItemUnitDataCollections { get; set; } = new List<OrderItemUnitDataCollection>();

    public virtual ICollection<OrderItemUnitScrap> OrderItemUnitScraps { get; set; } = new List<OrderItemUnitScrap>();

    public virtual ICollection<OrderItemUnitWorkElementHistory> OrderItemUnitWorkElementHistories { get; set; } = new List<OrderItemUnitWorkElementHistory>();

    public virtual ICollection<UserAttribute> UserAttributes { get; set; } = new List<UserAttribute>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}