// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class WorkElementTypeAttribute
{
    public int WorkElementTypeAttributeId { get; set; }

    public int WorkElementTypeId { get; set; }

    public string Name { get; set; }

    public bool IsRequiredAtSetup { get; set; }

    public bool IsRequiredAtRun { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual ICollection<BillOfProcessProcessWorkElementAttribute> BillOfProcessProcessWorkElementAttributes { get; set; } = new List<BillOfProcessProcessWorkElementAttribute>();

    public virtual WorkElementType WorkElementType { get; set; }

    public virtual ICollection<WorkElementTypeAttributeListItem> WorkElementTypeAttributeListItems { get; set; } = new List<WorkElementTypeAttributeListItem>();
}