// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ue_mes_data.Model;

public partial class WorkElementTypeAttributeListItem
{
    public int WorkElementTypeAttributeListItemId { get; set; }

    public int WorkElementTypeAttributeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime LastModifiedTime { get; set; }

    public DateTime LastModifiedTimeUtc { get; set; }

    public virtual WorkElementTypeAttribute WorkElementTypeAttribute { get; set; }
}